### ISSUE TITLE
Invalid number in NLP function or derivative detected.

### ISSUE THREAD

**Issue by selvi-aras** [jump-dev/Ipopt.jl#361]
Dear JuMP Community,

I am solving the following problem of maximizing a logsumexp function over an ellipsoid feasible set:

`using LinearAlgebra, JuMP, MosekTools, BARON,Ipopt, MathOptInterface, Dualization, Random`
`const MOI = MathOptInterface`
`Random.seed!(58)`
`n = 20`
`A = randn(n,n)`
`b = randn(n)`
`model = Model(Ipopt.Optimizer)`
`@variable(model, x[1:n], start = 1.0)`
`construct = randn(n, n)`
`Q = construct'construct`
`q = rand(n)`
`q0 = -10`
`@constraint(model, 0.5*x'*Q*x + q'*x + q0 <= 0)`
`@NLobjective(model, Max, log( sum( exp( sum(A[i,j]*x[j]  for j in 1:n) + b[i]) for i in 1:length(b)) ))`
`optimize!(model)`

This gives me the error **EXIT: Invalid number in NLP function or derivative detected.**

The problem is not fixed if I add some $10^{-10}$ value to the exp-inputs or if I try different starting points. I wanted to post this issue specifically to the `Ipopt.jl` issues, since this issue does not happen for BARON. (Note: Ipopt also does not have this issue for larger or smaller `n`, or many different seeds).

**Comment by odow** [comment]
It means that Ipopt tried to evaluate the objective at a point in the domain where the function or its derivative was undefined. 

This is known and expected behavior and is not a bug. Ipopt assumes the function is defined and twice differentiable at all points in the variable domain, _in `Float64` precision_.

Note that even if you have other constraints (like your quadratic) that should prevent this, Ipopt may evaluate infeasible points during the iteration process.

There are two likely cases:

 * Very large value of `x` causing `exp(Ax)` to be `Inf`
 * Very small value of `sum(...)`, causing the derivative of `log()` to be very large (probably `Inf`).

To fix, try adding variable bounds to `x` to keep it in a reasonable domain.

BARON does't encounter this issue because it uses a different algorithm.

Instead of using Ipopt, you could also try formulating this as a conic program. It looks like you might have tried this since you mentioned MOSEK, but if you have trouble, please post on https://discourse.julialang.org/c/domain/opt/13.

The tricks you'll need are
 * https://jump.dev/JuMP.jl/dev/tutorials/conic/tips_and_tricks/#Log-sum-exp
 * https://jump.dev/JuMP.jl/dev/tutorials/conic/tips_and_tricks/#Second-Order-Cone

**Comment by selvi-aras** [comment]
Thank you for your reply! This makes great sense to me. MOSEK wouldn't work in this specific example as I am maximizing the convex logsumexp function, but I indeed apply the exp-cone reformulation trick for its minimization. Moreover, BARON typically suffers from exploding `exp` terms. So, I think this probably is due to small values of `sum(...)`. I will confirm this, but I am closing the issue.

**Comment by odow** [comment]
Ah. I missed reading the `Max`. I just assumed you meant `Min`. 

Ipopt also assumes that the problem is convex, so if you pass it a non-convex problem, anything can happen.

Does it make sense to maximize log-sum-exp? Ipopt will also have trouble with large `exp`.

**Comment by selvi-aras** [comment]
Thank you for your reply! From Ipopt my only hope is a decent solution, not global. In my research, I am showing some cases where maximizing logsumexp (or convex functions, in general) is useful in ML.

**Comment by odow** [comment]
> From Ipopt my only hope is a decent solution, not global

Yeah so then I'd suggest: tight bounds, and a few different starting points.

> In my research, I am showing some cases where maximizing logsumexp (or convex functions, in general) is useful in ML.

Interesting :thinking:

**Comment by selvi-aras** [comment]
> Yeah so then I'd suggest: tight bounds, and a few different starting points.
> 
> >

Exactly! Many random starting points and prayers :)

**Comment by odow** [comment]
You can check if Ipopt found a solution by looking at `termination_status(model)`. I think it returns `NUMERICAL_ERROR` if it encountered a problem like that. (But you should double check.)

**Comment by selvi-aras** [comment]
Great to know, thank you very much for your support!
