### ISSUE TITLE
does not allow Ipopt_jll current version

### ISSUE THREAD

**Issue by JeffreySarnoff** [jump-dev/Ipopt.jl#364]
In a fresh directory
```
pkg> add Ipopt
...
pkg> status --outdated -m
⌅ [9cc047cb] Ipopt_jll v300.1400.1000+0 (<v300.1400.1200+0): Ipopt
```

**Comment by odow** [comment]
Just a heads up, we're very aware of these issues (https://github.com/jump-dev/SCS.jl/issues/274, https://github.com/jump-dev/HiGHS.jl/issues/165) because we (mostly @amontoison) are the ones who are maintaining the JLLs.

In most cases, they're already supported on `master`: 
https://github.com/jump-dev/Ipopt.jl/blob/1a20b678ecb55542fcd9ef7ed0b9b82c3b3eeb83/Project.toml#L14
but I just haven't gotten around to a release. For Ipopt, I was waiting for a resolution to https://github.com/jump-dev/Ipopt.jl/pull/363

**Comment by amontoison** [comment]
@odow 
I compiled the last release of MUMPS tonight.
I still need to fix the registration of SPRAL but I should be able to recompile Ipopt after.

We should have a new Ipopt_jll that works with LBT for all platforms and that propose SPRAL as linear solver.
I also asked Stefan Vigerske how we can compile Ipopt with `-03`.
